language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm install
  - npm install angular2piwik --save
  - npm install -g firebase-tools
  - npm install -g @angular/cli@1.6.4

script:
  - ng build --base-href "https://norahanimation.firebaseapp.com/"

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change